#!/usr/bin/env python3
"""Adaptive batch-size tuner for PhaseQFlow training.

Probes the GPU VRAM with descending batch sizes starting from a target
(default 256) until a dummy forward+backward pass succeeds without OOM.
Writes the result to a shell-sourceable env file so downstream scripts can
pick it up:

    source .batch_env && echo $OPTIMAL_BATCH

Usage
-----
    python scripts/utils/tune_batch_size.py            # start=256, write .batch_env
    python scripts/utils/tune_batch_size.py --start 128 --output my_batch.env
    python scripts/utils/tune_batch_size.py --dry_run   # print only, no write
"""

from __future__ import annotations

import argparse
import gc
import logging
import os
import sys
from pathlib import Path
from typing import List, Optional

logging.basicConfig(level=logging.INFO, format="[tune_batch] %(message)s")
log = logging.getLogger(__name__)

# Ordered candidates: start at highest and step down
_DEFAULT_CANDIDATES: List[int] = [256, 192, 128, 96, 64, 48, 32]

# Minimal dummy config for the probe
_ACTION_DIM = 7
_ACTION_CHUNK = 16
_FUSION_DIM = 512
_PHASE_DIM = 128


def _probe_batch(batch_size: int, device: str) -> bool:
    """Return True if a dummy forward+backward pass fits in VRAM."""
    try:
        import torch

        dev = torch.device(device)
        if dev.type == "cuda":
            torch.cuda.empty_cache()

        # Minimal linear model that resembles the policy's memory footprint
        # without importing the full policy (avoids heavy vision backbone init).
        model = torch.nn.Sequential(
            torch.nn.Linear(_FUSION_DIM, _FUSION_DIM * 4),
            torch.nn.SiLU(),
            torch.nn.Linear(_FUSION_DIM * 4, _FUSION_DIM),
            torch.nn.SiLU(),
            torch.nn.Linear(_FUSION_DIM, _ACTION_DIM * _ACTION_CHUNK),
        ).to(dev)
        opt = torch.optim.AdamW(model.parameters(), lr=1e-4)

        x = torch.randn(batch_size, _FUSION_DIM, device=dev)
        out = model(x)
        loss = out.mean()
        loss.backward()
        opt.step()
        opt.zero_grad()

        del model, opt, x, out, loss
        if dev.type == "cuda":
            torch.cuda.empty_cache()
        gc.collect()
        return True

    except RuntimeError as exc:
        if "out of memory" in str(exc).lower() or "CUDA out of memory" in str(exc):
            log.warning("  OOM at batch=%d", batch_size)
            try:
                import torch
                torch.cuda.empty_cache()
            except Exception:  # noqa: BLE001
                pass
            gc.collect()
            return False
        # Other errors (missing CUDA, etc.) — re-raise so they're visible
        raise


def find_optimal_batch(
    candidates: List[int],
    device: str = "cuda",
) -> Optional[int]:
    """Return the largest batch size from *candidates* that fits in VRAM."""
    for b in candidates:
        log.info("Probing batch_size=%d on device=%s ...", b, device)
        if _probe_batch(b, device):
            log.info("  -> OK. Selected batch_size=%d", b)
            return b
    return None


def main() -> None:
    parser = argparse.ArgumentParser(description="Adaptive batch-size tuner")
    parser.add_argument(
        "--start",
        type=int,
        default=256,
        help="Starting (maximum desired) batch size (default: 256)",
    )
    parser.add_argument(
        "--candidates",
        type=int,
        nargs="+",
        default=None,
        help="Override the full candidate list (descending order). "
             "If omitted, defaults to [start, 192, 128, 96, 64, 48, 32] "
             "filtered to ≤ start.",
    )
    parser.add_argument(
        "--device",
        default=os.environ.get("DEVICE", "cuda"),
        help="Torch device string (default: $DEVICE or 'cuda')",
    )
    parser.add_argument(
        "--output",
        default=".batch_env",
        help="Path to write the shell-sourceable env file (default: .batch_env)",
    )
    parser.add_argument(
        "--dry_run",
        action="store_true",
        help="Print the result but do not write the env file",
    )
    args = parser.parse_args()

    if args.candidates is not None:
        candidates = sorted(args.candidates, reverse=True)
    else:
        candidates = [b for b in _DEFAULT_CANDIDATES if b <= args.start]
        if args.start not in candidates:
            candidates = [args.start] + candidates

    log.info("Candidate batch sizes: %s", candidates)
    log.info("Device: %s", args.device)

    optimal = find_optimal_batch(candidates, device=args.device)

    if optimal is None:
        log.error("No batch size from %s fits in VRAM. Aborting.", candidates)
        sys.exit(1)

    env_content = (
        f"# Auto-generated by tune_batch_size.py — do not edit manually\n"
        f"export OPTIMAL_BATCH={optimal}\n"
        f"export BATCH_SIZE={optimal}\n"
    )

    print(env_content)

    if not args.dry_run:
        out_path = Path(args.output)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(env_content)
        log.info("Written to %s", out_path)
    else:
        log.info("[dry_run] env file NOT written (--dry_run)")


if __name__ == "__main__":
    main()
