#!/usr/bin/env python

"""Render ``stats.json`` into a booktabs LaTeX table (``ablation_table.tex``).

Outputs two LaTeX blocks:

1. A ``\\begin{tabular}`` main table whose rows are configs and columns are
   [Ident, PACE-A, PACE-B, PACE-C, PCAR, LIBERO-Long SR, LIBERO-Spatial SR,
   Delta vs baseline, p-value].
2. A caption + label. Requires the ``booktabs`` package (``\\usepackage{booktabs}``).

When ``placeholder_stats=true`` in ``stats.json`` the caption appends
"(CPU dry-run placeholder; numbers not from LIBERO)".

Usage
-----

    python scripts/paper/generate_latex_table.py \\
        --stats_json artifacts/ablation/stats.json \\
        --out paper_figures/ablation_table.tex
"""

from __future__ import annotations

import argparse
import json
import logging
import sys
from pathlib import Path
from typing import Any, Dict

logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
log = logging.getLogger("generate_latex_table")


CONFIG_FLAGS: Dict[str, Dict[str, bool]] = {
    "baseline": {"Ident": False, "A": False, "B": False, "C": False, "PCAR": False},
    "ident": {"Ident": True, "A": False, "B": False, "C": False, "PCAR": False},
    "a": {"Ident": True, "A": True, "B": False, "C": False, "PCAR": False},
    "b": {"Ident": True, "A": False, "B": True, "C": False, "PCAR": False},
    "c": {"Ident": True, "A": False, "B": False, "C": True, "PCAR": False},
    "ab": {"Ident": True, "A": True, "B": True, "C": False, "PCAR": False},
    "ac": {"Ident": True, "A": True, "B": False, "C": True, "PCAR": False},
    "bc": {"Ident": True, "A": False, "B": True, "C": True, "PCAR": False},
    "pace": {"Ident": True, "A": True, "B": True, "C": True, "PCAR": False},
    "pcar_only": {"Ident": True, "A": False, "B": False, "C": False, "PCAR": True},
    "full": {"Ident": True, "A": True, "B": True, "C": True, "PCAR": True},
    "pcar_noident": {"Ident": False, "A": False, "B": False, "C": False, "PCAR": True},
}


def _sr_cell(stat: Dict[str, Any]) -> str:
    """Render a LIBERO success-rate cell as ``mean +/- CI`` in percent."""
    if stat.get("mean") is None:
        return "--"
    return f"{100*stat['mean']:.1f} \\pm {100*(stat['ci95_half'] or 0.0):.1f}"


def _delta_cell(pair: Dict[str, Any]) -> str:
    """Render the paired delta-vs-baseline cell in percentage points."""
    if pair.get("delta_mean") is None:
        return "--"
    d = float(pair["delta_mean"]) * 100.0
    sign = "+" if d >= 0 else ""
    return f"{sign}{d:.1f}"


def _pvalue_cell(pair: Dict[str, Any]) -> str:
    """Render the p-value cell with typical significance-cut thresholds."""
    p = pair.get("p_value")
    if p is None:
        return "--"
    if p < 1e-3:
        return "$<$0.001"
    if p < 0.01:
        return f"{p:.3f}"
    return f"{p:.2f}"


def _row(cfg: str, stats: Dict[str, Any]) -> str:
    """Assemble one tabular row for config ``cfg``."""
    flags = CONFIG_FLAGS[cfg]
    long_cell = _sr_cell(stats["per_config"][cfg]["libero_long"])
    spat_cell = _sr_cell(stats["per_config"][cfg]["libero_spatial"])
    delta_cell = _delta_cell(stats["per_config"][cfg]["vs_baseline_long"])
    p_cell = _pvalue_cell(stats["per_config"][cfg]["vs_baseline_long"])
    check = lambda v: r"\checkmark" if v else " " # noqa: E731
    cfg_escaped = cfg.replace("_", r"\_")
    return (
        f" {cfg_escaped} & "
        f"{check(flags['Ident'])} & {check(flags['A'])} & {check(flags['B'])} "
        f"& {check(flags['C'])} & {check(flags['PCAR'])} & "
        f"${long_cell}$ & ${spat_cell}$ & ${delta_cell}$ & {p_cell} \\\\"
    )


def _build_tex(stats: Dict[str, Any]) -> str:
    """Return the full LaTeX ``table*`` block as a string."""
    placeholder = bool(stats.get("placeholder_stats"))
    caption_suffix = (
        r" (\emph{CPU dry-run placeholder; numbers are not LIBERO success rates})"
        if placeholder else ""
    )
    lines = [
        r"% Auto-generated by scripts/paper/generate_latex_table.py - Round 8.",
        r"% Requires: \usepackage{booktabs}",
        r"\begin{table*}[t]",
        r" \centering",
        r" \small",
        r" \begin{tabular}{lcccccccrr}",
        r" \toprule",
        r" Config & Ident & A & B & C & PCAR & "
        r"LIBERO-Long (\%) & LIBERO-Spatial (\%) & $\Delta$ Long (pp) & $p$ \\",
        r" \midrule",
    ]
    for cfg in stats["configs"]:
        lines.append(_row(cfg, stats))
    lines += [
        r" \bottomrule",
        r" \end{tabular}",
        r" \caption{Phase-Centric VLA ablation on LIBERO-Long (target) and "
        r"LIBERO-Spatial (control). Mean $\pm$ 95\% CI across "
        + str(stats.get("num_seeds", "N"))
        + r" seeds. $\Delta$ Long is the paired gain over the baseline; "
        r"$p$ is the two-sided paired $t$-test $p$-value." + caption_suffix + "}",
        r" \label{tab:ablation}",
        r"\end{table*}",
    ]
    return "\n".join(lines) + "\n"


def _parse_args() -> argparse.Namespace:
    """Parse CLI arguments."""
    p = argparse.ArgumentParser()
    p.add_argument("--stats_json", type=str, default="artifacts/ablation/stats.json")
    p.add_argument("--out", type=str, default="paper_figures/ablation_table.tex")
    return p.parse_args()


def main() -> int:
    """Load ``stats.json`` and write the rendered LaTeX table."""
    args = _parse_args()
    stats_path = Path(args.stats_json)
    if not stats_path.is_file():
        log.error("stats.json missing at %s - run aggregate_ablation.py first", stats_path)
        return 2

    stats = json.loads(stats_path.read_text())
    tex = _build_tex(stats)
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(tex)
    log.info("wrote %s (%d lines)", out, tex.count("\n") + 1)
    if stats.get("placeholder_stats"):
        log.warning("placeholder_stats=true - table caption is marked placeholder.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
